[package]
name = "rusterix"
version = "0.1.0"
edition = "2024"

[lib]
name = "rusterix"
path = "src/lib.rs"

[dependencies]
num-traits = "0.2"
syn = "2.0.114"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde-xml-rs = "0.6"
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
rand = "0.8"

[profile.dev]
opt-level = 0
debug = true